Section A: Data Structures & Control Structures

Question 1

In [4]:
# create a list of 5 integers
list=[10,20,30,40,50]
print(list)

[10, 20, 30, 40, 50]

In [7]:
# append function
l1=[]
l1.append(10)
l1.append(20)
l1.append(30)
l1.append(40)
l1.append(50)
print(l1)

[10, 20, 30, 40, 50]

In [8]:
# extend function
l1=["apple","banana","cherry"]
l2=["mango","orange","grapes"]
l1.extend(l2)
print(l1)
print(l2)

['apple', 'banana', 'cherry', 'mango', 'orange', 'grapes']
['mango', 'orange', 'grapes']

In [9]:
# insert function
list1=[10,20,30,40]
print(list1)
list1.insert(1,15) # insert(index,element)
list1.insert(3,25)
list1.insert(5,35)
print(list1)

[10, 20, 30, 40]
[10, 15, 20, 25, 30, 35, 40]

In [13]:
# remove function
list1=[10,20,30,40,50,60]
print(list1)
list1.remove(30)
list1.remove(60)
print(list1)

[10, 20, 30, 40, 50, 60]
[10, 20, 40, 50]

In [14]:
# pop function
l=[10,20,30,40,50]
print(l.pop())
print(l)

50
[10, 20, 30, 40]

In [15]:
# index function 
l=[10,20,30,40,50,60]
print(l.index(20))

1

In [17]:
# count function 
l=[10,20,10,10,30,40,50,10,60]
print(l.count(10))

4

In [18]:
# sort function 
l=[20,10,1,13,17,25,5,7]
l.sort()
print(l)

[1, 5, 7, 10, 13, 17, 20, 25]

In [21]:
# reverse function
l=[1,2,3,4,5,6]
l.reverse()
print(l)

[6, 5, 4, 3, 2, 1]

In [22]:
# clear function 
l=[10,20,30,40,50]
l.clear()
print(l)

[]

Question 2

In [24]:
# tuple that stores 3 students names 
students=("nannu","siri","binnu")
print(students)
students[1]=("cherry")
# we will get an typeerror.
# once a tuple is created we cannot change the content(add or remove).
# tuple is immutable

('nannu', 'siri', 'binnu')

TypeError: 'tuple' object does not support item assignment

Question 3

In [26]:
# Create a set of integers with some duplicate values
s={10,20,30,10,20,40,50}
print(s)
# set does not provide any duplicate values 
# set provides each and every value has its own hash values

{50, 20, 40, 10, 30}

Question 4

In [29]:
# Create a dictionary with the keys
dictionary={"name":"nannu","age":25,"city":"hyderabad"}
print(dictionary)
# updating age 
dictionary["age"]=22
print(dictionary)
# adding an new key email
dictionary["email"]="nanu@gamil.com"
# Printing  the final dictionary.
print(dictionary)

{'name': 'nannu', 'age': 25, 'city': 'hyderabad'}
{'name': 'nannu', 'age': 22, 'city': 'hyderabad'}
{'name': 'nannu', 'age': 22, 'city': 'hyderabad', 'email': 'nanu@gamil.com'}

Question 5

In [33]:
# checks if a person is eligible to vote
age=int(input("enter your age : "))
if age>=18:
    print("the person is eligible to vote.")
else:
    print("the person is not eligible to vote.")

enter your age :  19

the person is eligible to vote.

Question 6

In [37]:
# Given a marks variable print the grade
marks=int(input("enter your marks :"))
if marks >=90:
    print("Grade: A")
elif marks >=75:
    print("Grade: B")
elif marks >=50:
    print("Grade: C")
elif marks <50:
    print("Grade: Fail")

enter your marks : 89

Grade: B

Question 7

In [62]:
# Given a number check if it's positive and if it is also even.
A=int(input("enter your number:"))
if A > 0 and A %2==0:
    print(" A is an positve and even number ")
elif A <= 0:
    if A==0:
        print(" A value is zero ")
    else:
        print(" A value is negative ")
else:
    print("A is an positive and not even number")

enter your number: 4

 A is an positve and even number

Section B: Numpy

Question 8

In [66]:
# Create a scalar using np.array(5)
import numpy as np
a = np.array(5)
print("Scalar:",a)

# A 1D array with values 1 to 5
b = np.array([1,2,3,4,5])
print("1D Array:",b)

# A 2D array (2x3) with values from 10 to 60 in steps of 10
c = np.array([[10,20,30],[40,50,60]])
print("2D Array:",c)

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array: [[10 20 30]
 [40 50 60]]

Question 9

In [68]:
# Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
import numpy as np
a=np.random.randint(0,101,(4,4))
print(a)

[[54 43 35 21]
 [79 61 49 80]
 [15 89 89 93]
 [97  7  7 92]]

Question 10

In [70]:
# Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
import numpy as np 
import pandas as pd
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
df=pd.DataFrame(a)
df.columns=["A","B","C"]
print(df)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

Section C: Exploring Pandas

In [71]:
# Create a small DataFrame manually with 10 rows and columns
data={
    "Name":["abhi","binnu","kanna","mahesh","cherry","siri","nannu","swapna","arjun","rohith"],
    "Age":[21,23,22,20,21,23,19,25,26,29],
    "City":["khammam","adilabad","nirmal","hyderabad","nizamabad","metpally","siddipet","kamareddy","nalgonda","nagarkurnool"],
    "Salary": [30000, 20000, None, 25000, None, 45000, 35000, 50000, None, 50000]
}

In [85]:
# Loading data into dataframe 
import pandas as pd 
df =pd.DataFrame(data)
df

     Name  Age          City   Salary
0    abhi   21       khammam  30000.0
1   binnu   23      adilabad  20000.0
2   kanna   22        nirmal      NaN
3  mahesh   20     hyderabad  25000.0
4  cherry   21     nizamabad      NaN
5    siri   23      metpally  45000.0
6   nannu   19      siddipet  35000.0
7  swapna   25     kamareddy  50000.0
8   arjun   26      nalgonda      NaN
9  rohith   29  nagarkurnool  50000.0

In [73]:
# using .info to identifie the data types 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  7 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [86]:
# .describe gives an basic stats representation of data 
df.describe()

             Age        Salary
count  10.000000      7.000000
mean   22.900000  36428.571429
std     3.034981  12149.857926
min    19.000000  20000.000000
25%    21.000000  27500.000000
50%    22.500000  35000.000000
75%    24.500000  47500.000000
max    29.000000  50000.000000

In [79]:
# selecting name and city columns 
df[["Name","City"]]

     Name          City
0    abhi       khammam
1   binnu      adilabad
2   kanna        nirmal
3  mahesh     hyderabad
4  cherry     nizamabad
5    siri      metpally
6   nannu      siddipet
7  swapna     kamareddy
8   arjun      nalgonda
9  rohith  nagarkurnool

In [84]:
# Dropping City column
df.drop("City",axis=1)

     Name  Age   Salary
0    abhi   21  30000.0
1   binnu   23  20000.0
2   kanna   22      NaN
3  mahesh   20  25000.0
4  cherry   21      NaN
5    siri   23  45000.0
6   nannu   19  35000.0
7  swapna   25  50000.0
8   arjun   26      NaN
9  rohith   29  50000.0

In [87]:
# Filling the missing values in Salary column with the mean
df.fillna(df["Salary"].mean())

     Name  Age          City        Salary
0    abhi   21       khammam  30000.000000
1   binnu   23      adilabad  20000.000000
2   kanna   22        nirmal  36428.571429
3  mahesh   20     hyderabad  25000.000000
4  cherry   21     nizamabad  36428.571429
5    siri   23      metpally  45000.000000
6   nannu   19      siddipet  35000.000000
7  swapna   25     kamareddy  50000.000000
8   arjun   26      nalgonda  36428.571429
9  rohith   29  nagarkurnool  50000.000000

In [88]:
# Removing duplicate rows
# there is no duplicate rows in this data 
# so we cannot remove duplicate rows
df.drop_duplicates()

     Name  Age          City   Salary
0    abhi   21       khammam  30000.0
1   binnu   23      adilabad  20000.0
2   kanna   22        nirmal      NaN
3  mahesh   20     hyderabad  25000.0
4  cherry   21     nizamabad      NaN
5    siri   23      metpally  45000.0
6   nannu   19      siddipet  35000.0
7  swapna   25     kamareddy  50000.0
8   arjun   26      nalgonda      NaN
9  rohith   29  nagarkurnool  50000.0